### ISSUE TITLE
Proxying external host

### ISSUE THREAD

**Issue by sjdrc** [mesudip/nginx-proxy#19]
I'd like to use this to proxy services not running in docker, is this currently possible?

**Comment by mesudip** [comment]
It's designed for exposing docker containers only.

It's not impossible, as it is always possible to add a new `.conf` file in `conf.d` directory of nginx-proxy and update iptables rule to allow container to access host ports.  But the proxy will not manage ssl certificates or renew them.

**Comment by sjdrc** [comment]
Thanks for your quick reply - I appreciate it. Some users of jwilder/nginx-proxy were looking for a feature like this:

https://github.com/nginx-proxy/nginx-proxy/issues/998#issuecomment-373965627

A workaround was found by extending the template and running a dummy docker container. Would something like this be simple to implement with your proxy, and would you be able to assist with that?

And also thanks very much for this project, I switched to it for the simplicity of everything managed in a single service, and with the ability to proxy websockets. I've found it very useful.

**Comment by sjdrc** [comment]
Found a workaround, using https://hub.docker.com/r/oliverlorenz/proxy-pass to proxy the external host to docker, and then using your proxy to proxy that.
