### ISSUE TITLE
Generating new DH Parameters for SSL taking long time

### ISSUE THREAD

**Issue by johschmitz** [mesudip/nginx-proxy#2]
When running the container I am getting this:
```
Generating new DH Parameters for SSL as it's missing
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
```
It takes a lot of time.

This post suggest using `-dsaparam`
https://security.stackexchange.com/questions/95178/diffie-hellman-parameters-still-calculating-after-24-hours
Would that help here as well?

**Comment by johschmitz** [comment]
I think this is not critical, since it is just taking a couple of minutes or so.

**Comment by mesudip** [comment]
#6 
I've added the Dhparam information in Readme too
