### ISSUE TITLE
Unreachable Network

### ISSUE THREAD

**Issue by fero1xd** [mesudip/nginx-proxy#26]
I am starting nginx-proxy with this command 
```bash
docker run  --network code \
            --name nginx-proxy \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -p 80:80 \
            -d --restart always mesudip/nginx-proxy
```

And then starting another container like this
```bash
docker run --network code -e VIRTUAL_HOST="pg.lmao.dev -> :80" --expose 80 -d httpd
```

The domain is setup to point to my server and i have verified that it works.
After starting the second container and then running `docker logs` on the proxy container, i see an error saying " Unreachable Network".  Whats causing this error ?

**Comment by mesudip** [comment]
Hi @fero1xd, can you provide me full log of nginx-proxy container since startup?
That will help me debug the issue.

**Comment by mesudip** [comment]
@fero1xd , One reason might be because the proxy is not able to detect it's connected networks so that it's using "frontend" as fallback for network.

**Comment by fero1xd** [comment]
> Hi @fero1xd, can you provide me full log of nginx-proxy container since startup? That will help me debug the issue.

Sure,
```
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time

Using letsencrypt  url : https://acme-v02.api.letsencrypt.org/directory
Nginx is alive
No VIRTUAL_HOST       	Id:13ae06dc3806	    nginx-proxy
Nginx Reloaded Successfully
[SSL Refresh Thread]  Looks like there no ssl certificates, Sleeping until  there's one
Unreachable Network   	Id:30589a77fd47	    httpd
Unreachable Network   	Id:30589a77fd47	    httpd
```

**Comment by fero1xd** [comment]
> @fero1xd , One reason might be because the proxy is not able to detect it's connected networks so that it's using "frontend" as fallback for network.

I did docker inspect on the container, can confirm its using my network

**Comment by fero1xd** [comment]
> I tried reproducing it with the command you provided. Below is the logs.
> 
> ```
> [root@ip-xxx-test-infrastructure]# docker logs -f nginx-proxy
> Generating DH parameters, 2048 bit long safe prime, generator 2
> This is going to take a long time
> ............+........................***
> Using letsencrypt  url : https://acme-v02.api.letsencrypt.org/directory
> Nginx is alive
> Valid configuration   	Id:a955e4011f28	    gracious_booth
> -   http://pg.lmao.dev/
>       ->  http://172.18.0.3:80/
> No VIRTUAL_HOST       	Id:294987f9ff62	    nginx-proxy
> Nginx Reloaded Successfully
> [SSL Refresh Thread]  Looks like there no ssl certificates, Sleeping until  there's one
> ```
> 
> Restarting the containers might help. Sometimes if a container starts right before nginx starts reading configuration, it might not register it.
> 
> Can you provide me the type of machine you are running it on? I am testing it on amazon-ec2, where it has no issues.

Its ubuntu 2024

**Comment by mesudip** [comment]
> seems like this is a ubuntu 2024 issue.. I tried this with amazon linux and it worked fine for me.

Nginx-Proxy immediately requests container details on receiving events. I have noticed that in some system, docker-daemon  has a lag between sending events and updating its internal state.

Thanks for trying it out on different server. I'll add this in TODO.

**Comment by mesudip** [comment]
There is also an issue with
Docker version 27.1.1, build 63125853e3 running on archlinux
