### ISSUE TITLE
Secure websockets unable to connect

### ISSUE THREAD

**Issue by nospi** [mesudip/nginx-proxy#28]
I'm trying to get a websocket server running on the WSS protocol (can't connect to WS from a frontend running SSL). The websocket server is in a Go project, I'm trying to connect from a Vue3 project hosted in an NGINX server.

I've tried various combinations of configuration and can't for the life of me get this working. I am using `wscat` to test the connection, and can successfully connect to the server using either `ws://` or `http://` protocols. If I use `wss://` or `https://` I get the following error:

`error: write EPROTO 40989FF95A7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:`

I can't use these from a web browser though, as the site calling it is using HTTPS and therefore needs to be on the WSS protocol.

This is my current docker-compose environment on the websocket server:

`VIRTUAL_HOST=wss://{Hostname}:8080/ws -> :8080/ws`

I've also tried the following:

 - `VIRTUAL_HOST=ws://{hostname}:8080/ws`
 - `VIRTUAL_HOST=ws://{hostname}:8080`
 - `VIRTUAL_HOST=wss://{hostname}:8080`
 - `VIRTUAL_HOST=https://{hostname}:8080/ws`
 - `VIRTUAL_HOST={hostname}:8080`
 - `VIRTUAL_HOST={hostname}:8080/ws`

I've had a lot of trouble getting websockets through in the past but I am sure I've done it at some point.

I'm sure I must be misunderstanding something somewhere in the chain. I haven't experimented with a plain nginx server to manually edit configs and understand how it all works myself yet. Thanks for any advice or suggestions.

**Comment by nospi** [comment]
The issue was lack of sleep.. The 8080 port is not exposed by the reverse proxy; it's the port the websocket server runs on internally. The frontend needs to go through the reverse proxy on either 80 or 443... I apologise for any time wasted!

Changing my config to `VIRTUAL_HOST=wss://{hostname}/ws -> :8080/ws` did the trick, and I updated the frontend, no longer specifying port 8080 in the URL, going through the proxy instead. Works a charm!

**Comment by rodrigoross** [comment]
Hi @nospi could you show how your docker-compose for the websocket container ended up?

I`ve tried your solution `VIRTUAL_HOST=wss://{hostname}/ws -> :8080/ws` 

But looking in the nginx-proxy logs it shows:
```nginx.1     | 2025/05/31 04:40:17 [emerg] 462#462: invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf:160
nginx.1     | nginx: [emerg] invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf:160`
