### ISSUE TITLE
using real certs

### ISSUE THREAD

**Issue by matti** [mesudip/nginx-proxy#7]
how do I configure certs with my real cert .crt, .key -- ?

usecase: I need a real cert in localhost, can't use let's encrypt

**Comment by matti** [comment]
jwilder/nginx-proxy has that https://github.com/jwilder/nginx-proxy#ssl-support

**Comment by mesudip** [comment]
I haven't considered using the user's own certificate. I will add that option within a few days.

**Comment by matti** [comment]
AWESOME!!

**Comment by matti** [comment]
I think that jwilder proxy expects domains to have matching certs, like

app.mydomain.com.key/cert
test.mydomain.com.key/cert

would be awesome to have "wildcard" support if you have a wildcard cert

**Comment by mesudip** [comment]
I have made the required changes, view #8 for details.
